from safepush.config import AppConfig
from safepush.models import FileChange, ScanReport
from safepush.planner import build_plan


def test_grouped_plan_single_commit():
    cfg = AppConfig()
    cfg.git.commit_mode = "grouped"

    changes = [
        FileChange(path="src/app.py", status="M"),
        FileChange(path="README.md", status="??"),
    ]
    report = ScanReport(findings=[], scanned_files=2, blocked=False)

    plan = build_plan(changes, report, cfg)
    assert plan.blocked is False
    assert plan.commit_mode == "grouped"
    assert len(plan.commits) == 1
    assert "auto-generated by safepush deterministic planner" in plan.commits[0].message


def test_per_file_plan_multiple_commits():
    cfg = AppConfig()
    cfg.git.commit_mode = "per_file"

    changes = [
        FileChange(path="src/app.py", status="M"),
        FileChange(path="docs/guide.md", status="??"),
    ]
    report = ScanReport(findings=[], scanned_files=2, blocked=False)

    plan = build_plan(changes, report, cfg)
    assert plan.blocked is False
    assert plan.commit_mode == "per_file"
    assert len(plan.commits) == 2
    assert all(len(c.files) == 1 for c in plan.commits)


def test_blocked_if_scan_blocked():
    cfg = AppConfig()
    changes = [FileChange(path="src/app.py", status="M")]
    report = ScanReport(findings=[], scanned_files=1, blocked=True)

    plan = build_plan(changes, report, cfg)
    assert plan.blocked is True
    assert "Safety scan blocked execution." in plan.reasons