from __future__ import annotations

from typer.testing import CliRunner

from safepush.cli import app
from safepush.config import AppConfig
from safepush.models import FileChange, ScanFinding, ScanReport
from safepush.planner import ExecutionPlan, PlannedCommit


runner = CliRunner()


class _Repo:
    class _Head:
        is_detached = False

    class _Branch:
        name = "main"

    head = _Head()
    active_branch = _Branch()


def _base_patches(monkeypatch, *, changes: list[FileChange], report: ScanReport, cfg: AppConfig):
    monkeypatch.setattr("safepush.cli._load_cfg_or_exit", lambda: cfg)
    monkeypatch.setattr("safepush.cli.get_repo", lambda: _Repo())
    monkeypatch.setattr("safepush.cli.changed_and_untracked", lambda repo: changes)
    monkeypatch.setattr("safepush.cli.scan_changes", lambda _changes, _cfg: report)
    monkeypatch.setattr("safepush.cli.build_plan", lambda _changes, _report, _cfg, diff_summaries=None: ExecutionPlan(commits=[]))
    monkeypatch.setattr("safepush.cli.build_diff_summaries", lambda _repo, _changes: {})
    monkeypatch.setattr("safepush.cli.has_remote", lambda _repo, _remote: True)
    monkeypatch.setattr("safepush.cli.resolve_push_target", lambda _repo, remote, _branch: (remote, "main"))
    monkeypatch.setattr("safepush.cli.preview_git_actions", lambda *_args, **_kwargs: [])


def test_run_blocked_override_without_reason_blocks(monkeypatch):
    cfg = AppConfig()
    report = ScanReport(blocked=True, findings=[], scanned_files=1)
    changes = [FileChange(path="src/app.py", status="M")]
    _base_patches(monkeypatch, changes=changes, report=report, cfg=cfg)
    monkeypatch.setattr(
        "safepush.cli.scan_changes",
        lambda _changes, _cfg: ScanReport(
            blocked=True,
            scanned_files=1,
            findings=[  # overridable finding, but missing reason should still block
                ScanFinding(
                    kind="secret_pattern",
                    path="src/app.py",
                    detail="Generic API key",
                    severity="critical",
                )
            ],
        ),
    )

    result = runner.invoke(app, ["run", "--override"])
    assert result.exit_code == 3
    assert "Override requires --reason with explicit intent." in result.output


def test_run_scanner_error_override_still_blocked(monkeypatch):
    cfg = AppConfig()
    changes = [FileChange(path="src/app.py", status="M")]
    report = ScanReport(
        blocked=True,
        scanned_files=1,
        findings=[
            ScanFinding(
                kind="scanner_error",
                path="*",
                detail="Scanner failure",
                severity="critical",
            )
        ],
    )
    _base_patches(monkeypatch, changes=changes, report=report, cfg=cfg)

    result = runner.invoke(app, ["run", "--override", "--reason", "force"])
    assert result.exit_code == 3
    assert "non-overridable" in result.output


def test_interactive_abort_at_execute_confirmation_no_commit(monkeypatch):
    cfg = AppConfig()
    cfg.safety.dry_run_default = True
    changes = [FileChange(path="src/app.py", status="M")]
    report = ScanReport(blocked=False, scanned_files=1, findings=[])
    _base_patches(monkeypatch, changes=changes, report=report, cfg=cfg)
    monkeypatch.setattr(
        "safepush.cli.build_plan",
        lambda _changes, _report, _cfg, diff_summaries=None: ExecutionPlan(
            commit_mode="grouped",
            commits=[PlannedCommit(files=["src/app.py"], message="update(code): app\n\nauto-generated by safepush deterministic planner")],
        ),
    )

    called = {"apply": False}

    def _apply(*_args, **_kwargs):
        called["apply"] = True
        return []

    monkeypatch.setattr("safepush.cli.apply_execution_plan", _apply)
    result = runner.invoke(app, [], input="n\n")
    assert result.exit_code == 0
    assert called["apply"] is False
    assert "Dry-run preview" in result.output


def test_run_execute_push_disabled_commits_without_push(monkeypatch):
    cfg = AppConfig()
    cfg.git.push = False
    changes = [FileChange(path="src/app.py", status="M")]
    report = ScanReport(blocked=False, scanned_files=1, findings=[])
    _base_patches(monkeypatch, changes=changes, report=report, cfg=cfg)
    monkeypatch.setattr(
        "safepush.cli.build_plan",
        lambda _changes, _report, _cfg, diff_summaries=None: ExecutionPlan(
            commit_mode="per_file",
            commits=[PlannedCommit(files=["src/app.py"], message="update(code): app\n\nauto-generated by safepush deterministic planner")],
        ),
    )

    seen: dict[str, object] = {}

    def _apply(_repo, _plan, push, _remote, _branch):
        seen["push"] = push
        return ["abc123"]

    monkeypatch.setattr("safepush.cli.apply_execution_plan", _apply)
    result = runner.invoke(app, ["run", "--execute"])
    assert result.exit_code == 0
    assert seen["push"] is False
    assert result.output.index("Commit plan (per_file)") < result.output.index("Created 1 commit(s).")
    assert "Created 1 commit(s)." in result.output
    assert "Pushed to " not in result.output


def test_run_no_changes_exits_cleanly(monkeypatch):
    cfg = AppConfig()
    _base_patches(monkeypatch, changes=[], report=ScanReport(blocked=False, scanned_files=0, findings=[]), cfg=cfg)
    result = runner.invoke(app, ["run"])
    assert result.exit_code == 0
    assert "No changed or untracked files." in result.output


def test_run_missing_remote_blocks_execute_push(monkeypatch):
    cfg = AppConfig()
    cfg.git.push = True
    changes = [FileChange(path="src/app.py", status="M")]
    report = ScanReport(blocked=False, scanned_files=1, findings=[])
    _base_patches(monkeypatch, changes=changes, report=report, cfg=cfg)
    monkeypatch.setattr("safepush.cli.has_remote", lambda _repo, _remote: False)
    monkeypatch.setattr(
        "safepush.cli.build_plan",
        lambda _changes, _report, _cfg, diff_summaries=None: ExecutionPlan(
            commit_mode="grouped",
            commits=[PlannedCommit(files=["src/app.py"], message="update(code): app\n\nauto-generated by safepush deterministic planner")],
        ),
    )

    result = runner.invoke(app, ["run", "--execute"])
    assert result.exit_code == 2
    assert "Push is enabled but configured remote is missing." in result.output
