from __future__ import annotations

from collections import Counter
from pathlib import Path
from safepush.models import FileChange


def _category_for_path(path: str) -> str:
    p = path.lower()
    if p.endswith((".md", ".rst", ".txt")):
        return "docs"
    if "test" in p or p.endswith(("_test.py", ".spec.ts", ".test.ts", ".test.js")):
        return "test"
    if p.endswith((".yml", ".yaml", ".toml", ".json", ".ini")):
        return "config"
    if p.endswith((".py", ".ts", ".tsx", ".js", ".jsx", ".go", ".rs", ".java")):
        return "code"
    return "misc"


def _verb_for_statuses(statuses: list[str]) -> str:
    s = set(statuses)
    if s == {"??"}:
        return "add"
    if "??" in s and "M" in s:
        return "update"
    if s == {"M"}:
        return "update"
    if "D" in s:
        return "refactor"
    return "update"


def generate_grouped_commit_message(changes: list[FileChange]) -> str:
    if not changes:
        return "chore: no-op commit"

    statuses = [c.status for c in changes]
    verb = _verb_for_statuses(statuses)
    cats = Counter(_category_for_path(c.path) for c in changes)
    top_cat = cats.most_common(1)[0][0]

    scope = top_cat
    summary = f"{verb} {len(changes)} file(s)"
    detail = "auto-generated by safepush deterministic planner"

    return f"{verb}({scope}): {summary}\n\n{detail}"


def generate_per_file_commit_message(change: FileChange) -> str:
    verb = "add" if change.status == "??" else "update"
    scope = _category_for_path(change.path)
    name = Path(change.path).name
    return f"{verb}({scope}): {name}\n\nauto-generated by safepush deterministic planner"